### ISSUE TITLE
Wrong GHC version detected

### ISSUE THREAD

**Issue by awgn** [aaronallen8455/inventory#2]
Hello,

Now sure what's going on here, but here's what happens:

```
inventory: inventory: panic! (the 'impossible' happened)
  (GHC version 8.10.4:
        readHieFile: hie file versions don't match for file: /Users/admin/GitLab/VegoiaPlatform/Horta/.hie/Horta/Reader/Basic.hie Expected 8104 but got 8084
```

For some reason, it detects ghc 8.10.4, but the stack project I run it on is built on top of ghc 8.8.4:

```
stack exec ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.8.4
```

Thanks,
N.

**Comment by aaronallen8455** [comment]
This happens when inventory is compiled with a different ghc version than the project.
Try running `stack install inventory` from inside the project so that it uses the same version.
I clearly need to improve the error reporting for this.
